GET http://admin:admin@127.0.0.1:5984/sondaggi/_all_docs?include_docs=true
###

PUT http://admin:admin@127.0.0.1:5984/sondaggi/prova
{
	"_rev" : "2-ff1a73f303c2c4839bab8fa62499ee42",
    "domanda": "ciao",
    "attivo": true
}
###
DELETE http://admin:admin@127.0.0.1:5984/sondaggi/prova?rev=3-9be663cdc42d4fef0c9eae21584cb80b


###
curl --request GET \
	--url 'https://bing-image-search1.p.rapidapi.com/images/search?q=pizza&count=1' \
	--header 'x-rapidapi-host: bing-image-search1.p.rapidapi.com' \
	--header 'x-rapidapi-key: c03d71a603mshe424d6a21d8a6d8p1f001fjsn8da62c716452'

####